// Single source of truth for the five calculator pages: routing, SEO
// metadata, intent tier (drives the CTA placement), and which client-side
// math module the page loads. Cross-referenced by the home page, footer,
// and every internal "next calculator" link.
export default [
  {
    slug: 'mortgage-affordability-calculator',
    view: 'afford',
    icon: 'home',
    group: 'Buying a home',
    dropdownFeatured: true,
    navTitle: 'What you can afford',
    ctaLabel: 'Have someone check what I can afford',
    h1: 'How much mortgage can you afford?',
    cardDesc: 'Your maximum purchase price, tested the way a lender tests it.',
    metaTitle: 'How Much Mortgage Can I Afford? | Ontario Calculator',
    metaDescription: 'See your maximum purchase price using the real stress test, GDS/TDS ratios, and closing costs — not a rough guess. Free, no signup.',
    explainer: "This number comes from two tests a lender actually runs: whether the payment fits within about 39% of your income, and whether you'd still qualify if rates rose two points. Your down payment, existing debt, and where you're buying all move it.",
    intent: 'medium',
    relatedArticle: 'what-a-mortgage-actually-is',
    nextPage: { href: '/what-youll-need/', label: "See what you'll need to apply" }
  },
  {
    slug: 'mortgage-renewal-calculator',
    view: 'renew',
    icon: 'refresh',
    group: 'Managing a mortgage you already have',
    dropdownFeatured: true,
    navTitle: 'Your renewal options',
    ctaLabel: 'Have someone check this renewal offer',
    h1: 'Is your mortgage renewal offer fair?',
    cardDesc: "What signing your bank's offer actually costs versus shopping around.",
    metaTitle: 'Mortgage Renewal Calculator: Is Your Offer Fair?',
    metaDescription: "Compare your bank's renewal offer against today's best rate and see exactly what signing it costs you over the term.",
    explainer: "This compares the payment and remaining balance under your bank's offer against the same numbers at the rate available elsewhere, over the same term. The gap between the offered rate and the market rate drives almost all of it.",
    intent: 'high',
    intentQualifier: { key: 'renewalTiming', label: 'When does your term end?', options: ['Within 30 days', '1–3 months', '3–6 months', 'More than 6 months'] },
    relatedArticle: 'term-vs-amortization',
    nextPage: { href: '/what-happens-next/', label: 'See what happens next' }
  },
  {
    slug: 'mortgage-refinance-calculator',
    view: 'equity',
    icon: 'trending-up',
    group: 'Managing a mortgage you already have',
    dropdownFeatured: true,
    navTitle: 'Using your home equity',
    ctaLabel: 'Have someone check this refinance',
    h1: 'How much of your home equity can you use?',
    cardDesc: 'How much cash a refinance frees up, and what it really costs.',
    metaTitle: 'Mortgage Refinance & Equity Calculator | Ontario',
    metaDescription: 'See how much equity you can access, what a new payment looks like, and whether consolidating debt actually saves you money.',
    explainer: "This is what a new mortgage payment would look like if your highest-interest debt were rolled into it at today's rate, capped at 80% of your home's value. The rate gap between that debt and your new mortgage is what creates the savings.",
    intent: 'high',
    intentQualifier: { key: 'equityPurpose', label: 'What would the money be for?', options: ['Paying off high-interest debt', 'Renovation', 'A large purchase', 'Investing', 'Not sure yet'] },
    relatedArticle: 'down-payment-and-loan-to-value',
    nextPage: { href: '/what-youll-need/', label: "See what you'll need to apply" }
  },
  {
    slug: 'mortgage-penalty-calculator',
    view: 'penalty',
    icon: 'scissors',
    group: 'Managing a mortgage you already have',
    dropdownFeatured: true,
    navTitle: 'Leaving a mortgage early',
    ctaLabel: 'Have someone check this penalty estimate',
    h1: 'What would it cost to break your mortgage early?',
    cardDesc: 'The real penalty for breaking your term, as a range.',
    metaTitle: 'Mortgage Break Penalty Calculator | IRD Estimate',
    metaDescription: "Estimate the real cost of breaking your mortgage early — three months' interest or the rate differential, whichever applies.",
    explainer: "Fixed mortgages are charged the greater of three months' interest or the rate differential; variable mortgages only ever pay three months' interest. The gap between your rate and today's rate is what makes the penalty rise or fall.",
    intent: 'high',
    intentQualifier: { key: 'breakReason', label: 'Why are you considering breaking it?', options: ['Rate elsewhere is lower', 'Selling the home', 'Refinancing to consolidate debt', 'Just checking the number'] },
    relatedArticle: 'the-rate-you-pay-vs-the-rate-youre-tested-at',
    nextPage: { href: '/mortgage-refinance-calculator/', label: 'See what a refinance would look like instead' }
  },
  {
    slug: 'rent-vs-buy-calculator',
    view: 'rent',
    icon: 'swap',
    group: 'Buying a home',
    dropdownFeatured: true,
    navTitle: 'Renting compared to buying',
    h1: 'Is it better to rent or buy right now?',
    cardDesc: 'A five-year, side-by-side comparison of both paths.',
    metaTitle: 'Rent vs. Buy Calculator | Ontario, 5-Year View',
    metaDescription: 'A five-year, side-by-side comparison of renting and buying, including selling costs and what your down payment could earn invested.',
    explainer: "This weighs five years of home equity — price growth minus what's still owed minus selling costs — against five years of rent plus investing everything you would have spent on a down payment. Appreciation and investment return move it most.",
    intent: 'low',
    relatedArticle: 'what-a-mortgage-actually-is',
    nextPage: { href: '/mortgage-affordability-calculator/', label: 'See what you could actually afford' }
  },
  {
    slug: 'mortgage-payment-calculator',
    view: 'payment',
    icon: 'credit-card',
    group: 'Buying a home',
    navTitle: 'Your mortgage payment',
    ctaLabel: 'Have someone check this payment',
    h1: 'What would your mortgage payment be?',
    cardDesc: 'Your monthly, biweekly, and weekly payment, side by side.',
    metaTitle: 'Mortgage Payment Calculator | Ontario',
    metaDescription: 'See your exact monthly mortgage payment, plus accelerated biweekly and weekly options, using real Canadian semi-annual compounding.',
    explainer: 'Canadian mortgages compound semi-annually, not monthly like most online calculators assume — this uses the same math a lender actually runs. Accelerated biweekly and weekly options are shown because they quietly add one extra monthly payment a year, which adds up.',
    intent: 'medium',
    relatedArticle: 'term-vs-amortization',
    nextPage: { href: '/mortgage-affordability-calculator/', label: 'See what you could afford' }
  },
  {
    slug: 'land-transfer-tax-calculator',
    view: 'ltt',
    icon: 'receipt',
    group: 'Buying a home',
    navTitle: 'Land transfer tax',
    h1: 'How much land transfer tax will you pay?',
    cardDesc: 'Ontario and Toronto tax, plus the first-time buyer rebate.',
    metaTitle: 'Ontario Land Transfer Tax Calculator | Toronto Included',
    metaDescription: "Calculate Ontario land transfer tax, Toronto's municipal tax on top, and the first-time buyer rebates that can reduce both — due in cash on closing day.",
    explainer: 'Ontario charges land transfer tax on every home purchase, calculated in brackets that rise with price. Toronto is the only municipality that charges a second, matching tax on top. Both come due in cash on closing day, separate from your down payment.',
    intent: 'low',
    relatedArticle: 'closing-costs-are-more-than-the-down-payment',
    nextPage: { href: '/cmhc-insurance-calculator/', label: 'See what default insurance would add' }
  },
  {
    slug: 'cmhc-insurance-calculator',
    view: 'cmhc',
    icon: 'shield',
    group: 'Buying a home',
    navTitle: 'Default insurance premium',
    h1: 'What would your mortgage default insurance cost?',
    cardDesc: 'The premium, the sales tax on it, and whether you need it at all.',
    metaTitle: 'CMHC Mortgage Default Insurance Calculator | Canada',
    metaDescription: "Estimate your mortgage default insurance premium if you're putting down less than 20%, plus the Ontario sales tax due in cash on closing.",
    explainer: "Putting down less than 20% means a lender requires default insurance, priced as a percentage of your mortgage that rises the closer your down payment is to the legal minimum. The premium gets added to your mortgage, but the sales tax on it doesn't — that's due in cash.",
    intent: 'low',
    relatedArticle: 'down-payment-and-loan-to-value',
    nextPage: { href: '/land-transfer-tax-calculator/', label: 'See your land transfer tax' }
  },
  {
    slug: 'mortgage-stress-test-calculator',
    view: 'stress',
    icon: 'activity',
    group: 'Check your numbers',
    navTitle: 'The stress test',
    ctaLabel: 'Have someone check my numbers',
    h1: 'Would you pass the mortgage stress test?',
    cardDesc: "Your ratios at the rate you're actually tested at, not the rate you'd pay.",
    metaTitle: 'Mortgage Stress Test Calculator | Canada',
    metaDescription: 'Check whether your income qualifies for a given mortgage amount at the stress-tested rate — your rate plus 2%, or 5.25%, whichever is higher.',
    explainer: "Every federally regulated lender in Canada has to qualify you at a higher rate than you'll actually pay, using the same two ratios: GDS for housing costs alone, TDS for housing plus every other debt payment. This runs both against your numbers.",
    intent: 'medium',
    relatedArticle: 'the-rate-you-pay-vs-the-rate-youre-tested-at',
    nextPage: { href: '/mortgage-affordability-calculator/', label: 'See what you could afford' }
  },
  {
    slug: 'gds-tds-calculator',
    view: 'gdstds',
    icon: 'percent',
    group: 'Check your numbers',
    navTitle: 'GDS and TDS ratios',
    h1: 'What are your GDS and TDS ratios?',
    cardDesc: 'The two ratios every lender checks, and how much room is left.',
    metaTitle: 'GDS and TDS Ratio Calculator | Canada',
    metaDescription: 'Calculate your Gross Debt Service and Total Debt Service ratios — the two caps that decide what a lender will actually approve.',
    explainer: "GDS covers housing costs alone — mortgage, property tax, heat, and half of any condo fee — capped near 39% of gross income. TDS adds every other debt payment on top, capped near 44%. Most people who don't qualify are stopped by TDS, not GDS.",
    intent: 'low',
    relatedArticle: 'the-rate-you-pay-vs-the-rate-youre-tested-at',
    nextPage: { href: '/mortgage-affordability-calculator/', label: 'See what you could afford' }
  },
  {
    slug: 'amortization-calculator',
    view: 'amortization',
    icon: 'calendar',
    group: 'Managing a mortgage you already have',
    navTitle: 'Amortization & prepayment',
    ctaLabel: 'Have someone check my prepayment options',
    h1: 'How much would extra payments actually save you?',
    cardDesc: 'Real payoff time and interest saved from paying down faster.',
    metaTitle: 'Mortgage Amortization & Prepayment Calculator',
    metaDescription: "See exactly how much sooner your mortgage would be paid off, and how much interest you'd save, from an extra monthly payment or a one-time lump sum.",
    explainer: 'Extra payments go straight to principal, which is why they shorten a mortgage disproportionately to their size — every dollar off the balance early stops compounding years of interest on itself. This runs the real month-by-month math, not an estimate.',
    intent: 'medium',
    relatedArticle: 'term-vs-amortization',
    nextPage: { href: '/mortgage-renewal-calculator/', label: 'See your renewal options' }
  }
];
